/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ARRAY_H_
#define	_ARRAY_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ANY.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ARRAY */
typedef struct ARRAY {
	A_SEQUENCE_OF(ANY_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ARRAY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ARRAY;

#ifdef __cplusplus
}
#endif

#endif	/* _ARRAY_H_ */
#include "asn_internal.h"
