/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_BYTES_H_
#define	_BYTES_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UTF8String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BYTES */
typedef UTF8String_t	 BYTES_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BYTES;
asn_struct_free_f BYTES_free;
asn_struct_print_f BYTES_print;
asn_constr_check_f BYTES_constraint;
ber_type_decoder_f BYTES_decode_ber;
der_type_encoder_f BYTES_encode_der;
xer_type_decoder_f BYTES_decode_xer;
xer_type_encoder_f BYTES_encode_xer;
oer_type_decoder_f BYTES_decode_oer;
oer_type_encoder_f BYTES_encode_oer;
per_type_decoder_f BYTES_decode_uper;
per_type_encoder_f BYTES_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BYTES_H_ */
#include "asn_internal.h"
