/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_FLOAT128_H_
#define	_FLOAT128_H_


#include "asn_application.h"

/* Including external dependencies */
#include "REAL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FLOAT128 */
typedef REAL_t	 FLOAT128_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FLOAT128;
asn_struct_free_f FLOAT128_free;
asn_struct_print_f FLOAT128_print;
asn_constr_check_f FLOAT128_constraint;
ber_type_decoder_f FLOAT128_decode_ber;
der_type_encoder_f FLOAT128_encode_der;
xer_type_decoder_f FLOAT128_decode_xer;
xer_type_encoder_f FLOAT128_encode_xer;
oer_type_decoder_f FLOAT128_decode_oer;
oer_type_encoder_f FLOAT128_encode_oer;
per_type_decoder_f FLOAT128_decode_uper;
per_type_encoder_f FLOAT128_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FLOAT128_H_ */
#include "asn_internal.h"
