/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_INT64_H_
#define	_INT64_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* INT64 */
typedef INTEGER_t	 INT64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_INT64;
asn_struct_free_f INT64_free;
asn_struct_print_f INT64_print;
asn_constr_check_f INT64_constraint;
ber_type_decoder_f INT64_decode_ber;
der_type_encoder_f INT64_encode_der;
xer_type_decoder_f INT64_decode_xer;
xer_type_encoder_f INT64_encode_xer;
oer_type_decoder_f INT64_decode_oer;
oer_type_encoder_f INT64_encode_oer;
per_type_decoder_f INT64_decode_uper;
per_type_encoder_f INT64_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _INT64_H_ */
#include "asn_internal.h"
