/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PROPERTIES_H_
#define	_PROPERTIES_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "STRING8.h"
#include "ANY.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct PROPERTIES__Member {
	STRING8_t	 key;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PROPERTIES__Member;

/* PROPERTIES */
typedef struct PROPERTIES {
	A_SEQUENCE_OF(PROPERTIES__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PROPERTIES_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PROPERTIES;

#ifdef __cplusplus
}
#endif

#endif	/* _PROPERTIES_H_ */
#include "asn_internal.h"
