/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_STRING8_H_
#define	_STRING8_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* STRING8 */
typedef IA5String_t	 STRING8_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_STRING8_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_STRING8;
asn_struct_free_f STRING8_free;
asn_struct_print_f STRING8_print;
asn_constr_check_f STRING8_constraint;
ber_type_decoder_f STRING8_decode_ber;
der_type_encoder_f STRING8_encode_der;
xer_type_decoder_f STRING8_decode_xer;
xer_type_encoder_f STRING8_encode_xer;
oer_type_decoder_f STRING8_decode_oer;
oer_type_encoder_f STRING8_encode_oer;
per_type_decoder_f STRING8_decode_uper;
per_type_encoder_f STRING8_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _STRING8_H_ */
#include "asn_internal.h"
