/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_UINT32_H_
#define	_UINT32_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UINT32 */
typedef unsigned long	 UINT32_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UINT32;
asn_struct_free_f UINT32_free;
asn_struct_print_f UINT32_print;
asn_constr_check_f UINT32_constraint;
ber_type_decoder_f UINT32_decode_ber;
der_type_encoder_f UINT32_encode_der;
xer_type_decoder_f UINT32_decode_xer;
xer_type_encoder_f UINT32_encode_xer;
oer_type_decoder_f UINT32_decode_oer;
oer_type_encoder_f UINT32_encode_oer;
per_type_decoder_f UINT32_decode_uper;
per_type_encoder_f UINT32_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UINT32_H_ */
#include "asn_internal.h"
