/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "ARRAY.h"

static asn_TYPE_member_t asn_MBR_ARRAY_1[] = {
	{ ATF_ANY_TYPE | ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ARRAY_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ARRAY_specs_1 = {
	sizeof(struct ARRAY),
	offsetof(struct ARRAY, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ARRAY = {
	"ARRAY",
	"ARRAY",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ARRAY_tags_1,
	sizeof(asn_DEF_ARRAY_tags_1)
		/sizeof(asn_DEF_ARRAY_tags_1[0]), /* 1 */
	asn_DEF_ARRAY_tags_1,	/* Same as above */
	sizeof(asn_DEF_ARRAY_tags_1)
		/sizeof(asn_DEF_ARRAY_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_ARRAY_1,
	1,	/* Single element */
	&asn_SPC_ARRAY_specs_1	/* Additional specs */
};

