/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "BYTES.h"

/*
 * This type is implemented using UTF8String,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_BYTES_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (12 << 2))
};
asn_TYPE_descriptor_t asn_DEF_BYTES = {
	"BYTES",
	"BYTES",
	&asn_OP_UTF8String,
	asn_DEF_BYTES_tags_1,
	sizeof(asn_DEF_BYTES_tags_1)
		/sizeof(asn_DEF_BYTES_tags_1[0]), /* 1 */
	asn_DEF_BYTES_tags_1,	/* Same as above */
	sizeof(asn_DEF_BYTES_tags_1)
		/sizeof(asn_DEF_BYTES_tags_1[0]), /* 1 */
	{ 0, 0, UTF8String_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

