/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TMX-Types"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/asntype/TMX-Types.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "STRING8.h"

/*
 * This type is implemented using IA5String,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_STRING8_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER character map necessary */
};
static const ber_tlv_tag_t asn_DEF_STRING8_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (22 << 2))
};
asn_TYPE_descriptor_t asn_DEF_STRING8 = {
	"STRING8",
	"STRING8",
	&asn_OP_IA5String,
	asn_DEF_STRING8_tags_1,
	sizeof(asn_DEF_STRING8_tags_1)
		/sizeof(asn_DEF_STRING8_tags_1[0]), /* 1 */
	asn_DEF_STRING8_tags_1,	/* Same as above */
	sizeof(asn_DEF_STRING8_tags_1)
		/sizeof(asn_DEF_STRING8_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_STRING8_constr_1, IA5String_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

