/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeVehicleData"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-ProbeVehicleData.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_DriveAxleLocation_H_
#define	_DriveAxleLocation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DriveAxleLocation */
typedef long	 DriveAxleLocation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DriveAxleLocation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DriveAxleLocation;
asn_struct_free_f DriveAxleLocation_free;
asn_struct_print_f DriveAxleLocation_print;
asn_constr_check_f DriveAxleLocation_constraint;
ber_type_decoder_f DriveAxleLocation_decode_ber;
der_type_encoder_f DriveAxleLocation_encode_der;
xer_type_decoder_f DriveAxleLocation_decode_xer;
xer_type_encoder_f DriveAxleLocation_encode_xer;
oer_type_decoder_f DriveAxleLocation_decode_oer;
oer_type_encoder_f DriveAxleLocation_encode_oer;
per_type_decoder_f DriveAxleLocation_decode_uper;
per_type_encoder_f DriveAxleLocation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DriveAxleLocation_H_ */
#include "asn_internal.h"
