/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-Common.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_DYearMonth_H_
#define	_DYearMonth_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DYear.h"
#include "DMonth.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DYearMonth */
typedef struct DYearMonth {
	DYear_t	 year;
	DMonth_t	 month;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DYearMonth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DYearMonth;

#ifdef __cplusplus
}
#endif

#endif	/* _DYearMonth_H_ */
#include "asn_internal.h"
