/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-AddGrpB.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_Holiday_H_
#define	_Holiday_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Holiday {
	Holiday_weekday	= 0,
	Holiday_holiday	= 1
} e_Holiday;

/* Holiday */
typedef long	 Holiday_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Holiday;
asn_struct_free_f Holiday_free;
asn_struct_print_f Holiday_print;
asn_constr_check_f Holiday_constraint;
ber_type_decoder_f Holiday_decode_ber;
der_type_encoder_f Holiday_encode_der;
xer_type_decoder_f Holiday_decode_xer;
xer_type_encoder_f Holiday_encode_xer;
oer_type_decoder_f Holiday_decode_oer;
oer_type_encoder_f Holiday_encode_oer;
per_type_decoder_f Holiday_decode_uper;
per_type_encoder_f Holiday_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Holiday_H_ */
#include "asn_internal.h"
