/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-AddGrpB.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_LaneDataAttribute_addGrpB_H_
#define	_LaneDataAttribute_addGrpB_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LaneDataAttribute-addGrpB */
typedef struct LaneDataAttribute_addGrpB {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneDataAttribute_addGrpB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneDataAttribute_addGrpB;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneDataAttribute_addGrpB_H_ */
#include "asn_internal.h"
