/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-Common.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_Priority_H_
#define	_Priority_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Priority */
typedef OCTET_STRING_t	 Priority_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Priority_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Priority;
asn_struct_free_f Priority_free;
asn_struct_print_f Priority_print;
asn_constr_check_f Priority_constraint;
ber_type_decoder_f Priority_decode_ber;
der_type_encoder_f Priority_encode_der;
xer_type_decoder_f Priority_decode_xer;
xer_type_encoder_f Priority_encode_xer;
oer_type_decoder_f Priority_decode_oer;
oer_type_encoder_f Priority_encode_oer;
per_type_decoder_f Priority_decode_uper;
per_type_encoder_f Priority_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Priority_H_ */
#include "asn_internal.h"
