/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataManagement"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-ProbeDataManagement.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_TermDistance_H_
#define	_TermDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TermDistance */
typedef long	 TermDistance_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TermDistance_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TermDistance;
asn_struct_free_f TermDistance_free;
asn_struct_print_f TermDistance_print;
asn_constr_check_f TermDistance_constraint;
ber_type_decoder_f TermDistance_decode_ber;
der_type_encoder_f TermDistance_encode_der;
xer_type_decoder_f TermDistance_decode_xer;
xer_type_encoder_f TermDistance_encode_xer;
oer_type_decoder_f TermDistance_decode_oer;
oer_type_encoder_f TermDistance_encode_oer;
per_type_decoder_f TermDistance_decode_uper;
per_type_encoder_f TermDistance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TermDistance_H_ */
#include "asn_internal.h"
