/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPAT"
 * 	found in "../../../../../../../../../../src/tmx/tmx-message/j2735-202007/J2735-SPAT.asn"
 * 	`asn1c -fwide-types -fcompound-names -fincludes-quoted -fnative-types -no-gen-example`
 */

#ifndef	_TimeChangeDetails_H_
#define	_TimeChangeDetails_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TimeMark.h"
#include "TimeIntervalConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TimeChangeDetails */
typedef struct TimeChangeDetails {
	TimeMark_t	*startTime	/* OPTIONAL */;
	TimeMark_t	 minEndTime;
	TimeMark_t	*maxEndTime	/* OPTIONAL */;
	TimeMark_t	*likelyTime	/* OPTIONAL */;
	TimeIntervalConfidence_t	*confidence	/* OPTIONAL */;
	TimeMark_t	*nextTime	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeChangeDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeChangeDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_TimeChangeDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeChangeDetails_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _TimeChangeDetails_H_ */
#include "asn_internal.h"
