
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_APPLICATIONMESSAGEENUMTYPES_H_
#define INCLUDE_APPLICATIONMESSAGEENUMTYPES_H_

#include <tmx/common/types/Enum.hpp>

namespace tmx {
namespace message {
namespace v2x {

enum ApplicationTypes 
{
		NOAPPID = 0,
		CSW = 1,
		FCW = 2,
		EEBL = 3,
		INFLO = 4,
		RESCUMECS = 5,
		EPCW = 6,
		EVTRW = 7,
		TSPW = 8,
		RCI = 9,
		RCVW = 10,
		MD = 11,
		TSPWRD = 12,
		TSPWPOV = 13,
		RLVW = 14,
		GA = 15,
		CAS = 16
};

enum EventCodeTypes 
{
		NOEVENTID = 0,
		ApplicationActive = 1,
		ApplicationInactive = 2,
		EnteredArea = 3,
		ExitedArea = 4,
		DetectedArea = 5,
		NearsidePed = 6,
		FarsidePed = 7,
		LeftsidePed = 8,
		RightsidePed = 9,
		OnCurbsidePed = 10,
		InRoadwayPed = 11,
		AheadVeh = 12,
		AheadLeftVeh = 13,
		AheadRightVeh = 14,
		LeftVeh = 15,
		RightVeh = 16,
		BehindLeftVeh = 17,
		BehindRightVeh = 18,
		BehindVeh = 19,
		EventComplete = 20,
		InArea = 21,
		TrackingVeh = 22,
		ERROR = 23,
		RCVWAlert = 24,
		RCVWWarning = 25,
		MDAlert = 26,
		MDWarning = 27,
		MDAdvisory = 28,
		Landing = 29,
		Arrived = 30,
		Leaving = 31,
		InRoadwayFwdCenterPed = 32,
		InRoadwayFwdCurbPed = 33,
		InRoadwayRearCenterPed = 34,
		InRoadwayRearCurbPed = 35,
		RLVWAlert = 36,
		RLVWWarning = 37,
		GAAdvisory = 38,
		GAAlert = 39,
		GAWarning = 40,
		RCVW2Available = 41,
		RCVW2ApproachInform = 42,
		RCVW2ApproachWarning = 43,
		RCVW2HRIWarning = 44,
		RCVW2Error = 45,
		CASReady = 46,
		CASSafing = 47,
		CASSafed = 48,
		CASCaution = 49
};

enum Severity 
{
		Info = 0,
		Inform = 1,
		Warning = 2,
		Audio = 3
};
			
} /* End namespace v2x */
} /* End namespace messages */
} /* End namespace tmx */

#endif /* INCLUDE_APPLICATIONMESSAGEENUMTYPES_H_ */
	
