
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_
#define INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_

#include <tmx/common/types/Enum.hpp>

namespace tmx {
namespace messages {
namespace v2x {

enum DataCodeId {
    NOEVENTID = 0,
    EPCW = 1,
    VTRW = 2
};

enum StageTypes {
    None = 0,
    Detected = 1,
    Entering = 2,
    InCenter = 3,
    Exiting = 4
};

} /* End namespace v2x */
} /* End namespace messages */
} /* End namespace tmx */

#endif /* INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_ */
	