
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_LOCATIONMESSAGEENUMTYPES_H_
#define INCLUDE_LOCATIONMESSAGEENUMTYPES_H_

#include <tmx/common/types/Enum.hpp>
	
namespace tmx {
namespace message {
namespace v2x {

enum FixTypes 
{
		Unknown = 0,
		NoFix = 1,
		TwoD = 2,
		ThreeD = 3
};
		
enum SignalQualityTypes
{
		Invalid = 0,
		GPS = 1,
		DGPS = 2,
		PPS = 3,
		RealTimeKinematic = 4,
		FloatRTK = 5,
		DeadReckoning = 6,
		ManualInputMode = 7,
		SimulationMode = 8
};
		

} /* End namespace v2x */
} /* End namespace message */
} /* End namespace tmx */

#endif /* INCLUDE_LOCATIONMESSAGEENUMTYPES_H_ */
	