/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_LOCATIONMESSAGEENUMTYPES_H_
#define INCLUDE_LOCATIONMESSAGEENUMTYPES_H_

#include <tmx/common/types/Enum.hpp>
	
namespace tmx {
namespace message {
namespace v2x {

enum FixTypes 
{
		Unknown = 0,
		NoFix = 1,
		TwoD = 2,
		ThreeD = 3
};

/*!
 * @brief Copied from https://gitlab.com/gpsd/gpsd/-/blob/master/include/gps.h?ref_type=heads
 */
enum SignalQualityTypes
{
		Invalid = 0,
		GPS = 1,
		DGPS = 2,
		RealTimeKinematic = 3,
		FloatRTK = 4,
		DeadReckoning = 5,
		GNSSwithDR = 6,
		TimeOnly = 7,
		SimulationMode = 8,
	    PPS = 9
};
		

} /* End namespace v2x */
} /* End namespace message */
} /* End namespace tmx */

#endif /* INCLUDE_LOCATIONMESSAGEENUMTYPES_H_ */
	