
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_VEHICLEPARAMETERENUMTYPES_H_
#define INCLUDE_VEHICLEPARAMETERENUMTYPES_H_

#include <tmx/common/types/Enum.hpp>

	
namespace tmx {
namespace message {
namespace v2x {

enum class GearState 
{
		GearUnknown = 0,
		Park = 1,
		Reverse = 2,
		Drive = 3,
		Other = 4
};

enum class TurnSignalState 
{
		SignalUnknown = 0,
		Off = 1,
		Left = 2,
		Right = 3,
		Hazard = 4
};

enum class WiperState
{
		WiperUnknown = 0,
		Off = 1,
		Delay = 2,
		Low = 3,
		High = 4
};

enum class DoorState
{
		Closed = 0,
		Open = 1
};
		

enum class GenericState 
{
		Inactive = 0,
		Active = 1
};

enum VehicleParameter
{
		ParameterNA = 0,
		GearPosition = 1,
		TurnSignal = 2,
		Brake = 3
};

enum VehicleParameterState
{
		StateNA = 0,
		Gear_Park = 1,
		Gear_Reverse = 2,
		Gear_Drive = 3,
		Gear_Other = 4,
		Turn_Off = 5,
		Turn_Left = 6,
		Turn_Right = 7,
		Brake_On = 8,
		Brake_Off = 9
};

} /* End namespace V2X */
} /* End namespace messages */
} /* End namespace tmx */
		
#endif /* INCLUDE_VEHICLEPARAMETERENUMTYPES_H_ */
	